name: Deploy to /var/www/html

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy files to /var/www/html
        run: sudo cp -r * /var/www/html
